[package]
name = "kornia-slam"
version = "0.1.0"
edition = "2024"
description = "Spatial runtime for real-time pose estimation, mapping, and agent interaction."

[dependencies]
kornia-3d = { git = "https://github.com/kornia/kornia-rs", branch = "feat/stereo-rectifier-left-rotation" }
kornia-algebra = { git = "https://github.com/kornia/kornia-rs", branch = "feat/stereo-rectifier-left-rotation" }
kornia-image = { git = "https://github.com/kornia/kornia-rs", branch = "feat/stereo-rectifier-left-rotation" }
kornia-imgproc = { git = "https://github.com/kornia/kornia-rs", branch = "feat/stereo-rectifier-left-rotation" }
kornia-sensors = { path = "../kornia-sensors" }